### ISSUE TITLE
[RFE] Document how to use the seccomp policy advisor gadget and how it integrates with the operator

### ISSUE THREAD

**Issue by marga-kinvolk** [kinvolk/inspektor-gadget#266]
## Current situation

I was trying to create a demo of the seccomp policy advisor gadget and I had to reconstruct how it's supposed to work based on the comments on a bunch of different pull requests. There are no docs on how to use this gadget.

## Starting point

This is what I managed to understand from the PRs. This could be used to get started with the docs, although there might be errors or omissions.

### Basic usage

The gadget currently requires creating a tracing CRD, like this:
```
apiVersion: gadget.kinvolk.io/v1alpha1
kind: Trace
metadata:
  name: seccomp
  namespace: gadget
spec:
  node: node-name
  gadget: seccomp
  filter:
    namespace: namespace-name
    podname: pod-name
  runMode: Manual
  outputMode: Status
```

The names of the node, namespace and pod are all compulsory. Once this trace is created in the cluster, it needs to be annotated to get the gadget started, with:

```
kubectl annotate -n gadget trace/seccomp gadget.kinvolk.io/operation=start
```

After that, there needs to be interaction with the pod (possibly including creating the pod from scratch, to capture the syscalls that are done on start), so that all approved syscalls are captured.  Once all desired activity has been captured, the policy can be generated with:

```
kubectl annotate -n gadget trace/seccomp gadget.kinvolk.io/operation=generate
```

If the `outputMode` was status as shown above, the trace CRD will now contain the generated policy.

### Integration with Kubernetes Security Profiles Operator

The [Kubernetes Security Profiles Operator](https://github.com/kubernetes-sigs/security-profiles-operator) defines a seccompprofile custom resource. It is useful for the seccomp gadget to output a seccomp profile directly as a seccompprofile resource. In this way, users don't have to copy/paste the output of the seccomp gadget into a seccompprofile resource.

In this case, the CRD should use `ExternalResource` as the `outputMode` and set the name of the desired `seccompprofile` CRD in the `output` field:
```
apiVersion: gadget.kinvolk.io/v1alpha1
kind: Trace
metadata:
  name: seccomp
  namespace: gadget
spec:
  node: node-name
  gadget: seccomp
  filter:
    namespace: namespace-name
    podname: pod-name
  runMode: Manual
  outputMode: ExternalResource
  output: gadget/myseccomp
```

Install the seccomp operator with the following instructions:
https://github.com/kubernetes-sigs/security-profiles-operator/blob/master/installation-usage.md#install-operator

```
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.4.1/cert-manager.yaml
kubectl --namespace cert-manager wait --for condition=ready pod -l app.kubernetes.io/instance=cert-manager
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/master/deploy/operator.yaml
```

Then, following the steps above for capturing the calls and generating the policy should lead to a generated `seccompprofile` CRD.  This profile can be used as a security context in the pod, by modifying its definition to include:

```
apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  namespace: namespace-name
  labels:
    app: my-app
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: operator/gadget/myseccomp.json
  containers:
  ...
```

And then restarting the pod with the policy active.
