### ISSUE TITLE
Missing annotations in SeccompProfile generated by seccomp gadget

### ISSUE THREAD

**Issue by alban** [kinvolk/inspektor-gadget#341]
## Description

The seccomp profile generated by the seccomp gadget should contain annotations so that users can know which pod was used to generate it:

```
metadata:
  annotations:
    seccomp.gadget.kinvolk.io/container: shell01
    seccomp.gadget.kinvolk.io/container-id: 305a4e6d501f8cbebda8f5659a30cb4664f864cda14e2ead996a723e01098296
    seccomp.gadget.kinvolk.io/node: local
    seccomp.gadget.kinvolk.io/pid: "57738"
    seccomp.gadget.kinvolk.io/pod: default/shell01
    seccomp.gadget.kinvolk.io/trace: gadget/trace1
```

However, the aforementioned annotations are only added when the SeccompProfile was generated automatically upon pod termination. If the SeccompProfile is generated manually via the "generate" operation, the information is missing.

## Impact

This makes it more difficult to write a Headlamp plugin for the seccomp gadget.

## Expected behavior

Generated SeccompProfiles have annotations such as `seccomp.gadget.kinvolk.io/pod` regardless of how it was generated.

## Additional information

cc @ashu8912
