### ISSUE TITLE
[RFE] Revisit mountPropagation: Bidirectional for /run mount in pod manifest

### ISSUE THREAD

**Issue by invidian** [kinvolk/inspektor-gadget#452]
## Current situation

Right now gadget container in pod has the following mount:
```
    volumeMounts:
    - mountPath: /run
      mountPropagation: Bidirectional
      name: run
```

This has caused #433.

@alban said that he does not know why `mountPropagation: Bidirectional` is used, so it may not be necessary.

## Impact

Right now this configuration part does not have explicit justification or tests, which makes it more difficult to maintain. It may also cause some further issues in the future.

## Ideal future situation

Either use of `mountPropagation: Bidirectional` is explicitly justified and/or tested or is removed as not needed anymore.
