### ISSUE TITLE
[RFE] Run integration-tests on AKS

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#725]
## Current situation

We are not running the integration-tests on AKS.

## Impact

We are not sure if all the gadgets are correctly working on AKS (they should) and most importantly, we are not guaranteeing that we are not introducing regressions.

## Implementation options

As an initial idea, it could use the same cluster all the time as we are doing for ARO. However, it is worth investigating how much time it requires to create a new cluster every time and consider that approach.

BTW, it could run in parallel with the minikube test like this:

```yaml
  test-integration:
    name: Integration tests
    ...
    strategy:
      matrix:
        k8s-distro: [minikube, aks]
    ...
    steps:
    ...
    - if: matrix.k8s-distro == 'minikube'
      name: Setup Minikube
      ...
    - if: matrix.k8s-distro == 'aks'
      name: Authenticate and set AKS cluster context
      uses: azure/aks-set-context@v1
      env:
        CLUSTER_NAME: "inspektor_gadget_ci_cluster"
        CLUSTER_RESOURCE_GROUP: "inspektor-gadget-ci-rg"
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
```
