### ISSUE TITLE
Do not use "fail to ...", "error ...(ing)" in error messages

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [kinvolk/inspektor-gadget#881]
Having the "fail to", "error ..." prefixes causes error messages to be weird as they end up being something like: "fail to foo: error while X: failed to ...", we can remove those prefixes and only indicate the reason. 

Ref https://github.com/kinvolk/inspektor-gadget/pull/821/files#r957269992.

**Comment by invidian** [comment]
Here is some simple [semgrep](https://semgrep.dev/) rules which I always use to catch things like that:
```yaml
rules:
  - id: bad-error-wrap-wording
    patterns:
      - pattern-regex: fmt\.Errorf\(".?([Ff]ailed|[]Uu]nable|[Cc]ould|([Ee]rror)|([Cc]an[ ]?not))
    message: Phrases "fail", "failed", "unable", "could not", "cannot", "can not" should not be used when wrapping errors. Use verb in continuous form instead!
    languages: [go]
    severity: ERROR
  - id: printed-messages-must-be-captialized
    patterns:
      - pattern-regex: (fmt.Print(ln|f)|\bt\.(Error|Fatal|Log)(|f))\("[a-z]
    message: Printed messages must be capitalized.
    languages: [go]
    severity: ERROR
  - id: strings-must-be-quoted-using-q
    patterns:
      - pattern-regex: "'%s'"
    message: When formatting, strings must be quoted using %q instead of e.g. '%s'.
    languages: [go]
    severity: ERROR
  - id: error-wrapping-must-be-preceded-by-space
    patterns:
      - pattern-regex: '[^ ]%w'
    message: When wrapping errors, %w must be preceded by space.
    languages: [go]
    severity: ERROR
  - id: files-must-not-have-trailing-whitespace
    patterns:
      - pattern-regex: '[[:blank:]]$'
    message: Files must not have any trailing whitespace.
    languages: [generic]
    severity: ERROR
  - id: files-must-not-have-trailing-newlines
    patterns:
      - pattern-regex: '\n\n\Z'
    message: Files must not have any trailing newlines.
    languages: [generic]
    severity: ERROR
  - id: all-lines-must-end-with-newline
    patterns:
      - pattern-regex: '\S\z'
    message: All lines must end with newline.
    languages: [generic]
    severity: ERROR
```
